name: Java CI with Gradle

on:
  push:
    branches: [ v5 ]
  pull_request:
    branches: [ v5 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: pwd
      run: pwd
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle User Files
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
    - name: Cache Gradle Files
      uses: actions/cache@v1
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: PlotSquared
        path: /home/runner/work/PlotSquared/PlotSquared
